### ISSUE TITLE
Default log level with Tinkerbell Helm Chart is too low

### ISSUE THREAD

**Issue by mmeier86** [tinkerbell/tinkerbell#197]
Hello Tinkerbell team,

I'm currently setting up a Tinkerbell test deployment with v0.18.0 of the Helm chart. I'm setting it up in an Ubuntu 24.04 VM running in k3s, with kube-vip as the service load balancer. This is a single node setup.

This is my `values.yaml` file:
```
publicIP: "203.0.113.11"
trustedProxies:
  - "10.42.0.0/24"
artifactsFileServer: "http://203.0.113.11:8080"
deployment:
  envs:
    tinkController:
      enableLeaderElection: false
    smee:
      dhcpMode: "proxy"
    globals:
      enableRufioController: false
      enableSecondstar: false
#      logLevel: 3
  init:
    enabled: true
service:
  lbClass: ""
hookos:
  service:
    lbClass: ""
  kernelVersion: "6.6"
  persistence:
    existingClaim: "hookos-volume"
kubevip:
  enabled: false
```

And I was seeing an issue. Another VM in the same subnet was trying to netboot and failing, not getting a DHCP response with netboot settings. The problem was: There was absolutely no indication that anything at all had happened in the Tinkerbell logs. I assumed that the issue must be with my k3s cluster setup, that somehow the DHCP request wasn't finding its way to Smee.
After a couple of hours of debugging, I realized that I never tried to increase the log level for Tinkerbell. I added the `logLevel: 3` option which is commented out above, and then I finally got a lot of output in the logs, among it this error:

```
{"time":"2025-06-07T22:04:38.322503545Z","level":"-1","caller":"smee/internal/dhcp/handler/proxy/proxy.go:211","msg":"Ignoring packet","service":"smee","mac":"10:66:6a:07:8d:0d","xid":"0xfd39e0af","interface":"macvlan0","error":"failed to convert hardware to DHCP data: no IP data"}
```
This error isn't the issue of the bug though, I haven't investigated it yet, probably just some error in my Hardware manifest.

The actual issue: I would have expected this error to show in the logs on the default log level. Instead, I didn't see anything in the logs and went on a wild goose chase.

Perhaps the default log level in the chart could be increased? Or perhaps the level of that error in general, so it shows at the default log level?
