### ISSUE TITLE
Small inconsistency in Smee with allowPXE: false

### ISSUE THREAD

**Issue by mmeier86** [tinkerbell/tinkerbell#223]
Hello Tinkerbell team,

while working on my Pi 4 Pi PXE -> UEFI -> iPXE -> Tinkerbell process, I found a small inconsistency in Smee's behaviour when `interfaces[].netboot.allowPXE` is set to `false`. In this mode, Smee still hands out the `snp.efi` file over TFTP when asked for it, but when trying to fetch the `auto.ipxe` script via HTTP in the next step, it returns a 404 and the logs say that the hardware is not allowed to PXE.

I've got the following Hardware object:
```yaml
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: testpi
spec:
  metadata:
    instance:
      id: e4:5f:01:bc:f4:ce
      ips:
        - address: 192.0.2.2
      allow_pxe: false
      hostname: testpi
      operating_system:
        distro: "ubuntu"
        version: "24.04"
  disks:
  - device: /dev/sda
  interfaces:
  - dhcp:
      arch: arm64
      hostname: testpi
      mac: e4:5f:01:bc:f4:ce
      ip:
        address: 192.0.2.2
        netmask: 255.255.255.0
      name_servers:
      - 192.0.2.250
      uefi: true
    netboot:
      allowPXE: false
      allowWorkflow: true
```
Smee is configured in DHCP proxy mode. As I'm trying to netboot a diskless Pi here, all of the DHCP is being done by dnsmasq, as I need TFTP support for the initial boot files for the Pi. Once I've booted into the UEFI firmware, that starts a new round of DHCP requests and gets back the filename `snp.efi` with the IP of Tinkerbell as the TFTP server. Tinkerbell then happily delivers the file:
```json
{"time":"2025-06-26T19:02:11.0653023Z","level":"8","caller":"smee/internal/ipxe/binary/tftp.go:117","msg":"file serve failed","service":"smee","service":"github.com/tinkerbell/smee","event":"get","filename":"snp.efi","uri":"snp.efi","clie
nt":{"IP":"192.0.2.2","Port":1970,"Zone":""},"macFromURI":"","logger":"github.com/tinkerbell/ipxedust","err":"sending block 0: code=8, error: User aborted the transfer\u0000","b":0,"contentSize":267264}                           
{"time":"2025-06-26T19:02:11.176436104Z","level":"0","caller":"smee/internal/ipxe/binary/tftp.go:122","msg":"file served","service":"smee","service":"github.com/tinkerbell/smee","event":"get","filename":"snp.efi","uri":"snp.efi","client":{"IP":"192.0.2.2","Port":1971,"Zone":""},"macFromURI":"","logger":"github.com/tinkerbell/ipxedust","bytesSent":267264,"contentSize":267264}
```
In the next step, iPXE runs another DHCP request and gets back `http://192.0.2.20:7171/auto.ipxe`, where the IP is Tinkerbell's IP. And this time, Smee seems to recognize that the host isn't actually allowed to PXE and does not send the iPXE script, instead returning 404:
```json
{"time":"2025-06-26T19:02:24.911697105Z","level":"0","caller":"smee/internal/ipxe/script/ipxe.go:169","msg":"the hardware data for this machine, or lack there of, does not allow it to pxe","service":"smee","client":"192.0.2.2:42502","error":null}
{"time":"2025-06-26T19:02:24.911752728Z","level":"0","caller":"smee/internal/ipxe/http/middleware.go:37","msg":"response","service":"smee","method":"GET","uri":"/auto.ipxe","client":"192.0.2.2","duration":160896,"status":404}
```

This behaviour seems a bit confusing, handing out the iPXE binaries even with PXE disabled, but then not handing out the iPXE script.

But then again, I also see the danger that there might be deployments out there relying on the iPXE binary being served even with `allowPXE` set to `false`. So I'd be perfectly fine with closing as "Won't fix", but wanted to at least mention it.
