### ISSUE TITLE
Calls from not TrustedProxies return 500

### ISSUE THREAD

**Issue by eidmantas** [tinkerbell/tinkerbell#456]
Hello,

We've been running into an issue where we're getting 500, "no hardware found" using hegel helm chart.

Yesterday managed to get it working:
- by creating an additional hardware object.
- today changed HEGEL_TRUSTED_PROXIES to `0.0.0.0/0` to allow debug requests - started working again.
Seems unrelated at first (though I see [forwarding per nginx is intended]).(https://github.com/tinkerbell/charts/blob/20cdc1260fd90710f051e436fe713cf93f7bb130/tinkerbell/stack/docs/arch.md?plain=1#L11) 
```
tcp            LISTEN           0                511                               0.0.0.0:50061                          0.0.0.0:*              users:(("nginx",pid=685852,fd=6),("nginx",pid=685837,fd=6)) ` )
```

Haven't yet had time to go through the mechanism from which using kubernetes backend info is collected. 
Was wondering if maybe somebody has seen similar behaviour recently? 

Wondering if there's some actual problem collecting the hardware info, or are we just getting some unhandled error due to blocked X-Forwarded-For. 

Will look into our tink-stack as it currently seems to be forwarding 50061 for Hegel, maybe we just had our ranges set-up wrong and this is an unhandled error in the code. 

```
  containers:
    - args:
        - '--backend=kubernetes'
        - '--http-addr=:50061'
        - '--kubernetes-namespace=tinkerbell'
      env:
        - name: HEGEL_TRUSTED_PROXIES
          value: 10.5.0.0/16
```

```
{
    "level": "error",
    "client_ip": "10.5.0.23",
    "method": "GET",
    "status_code": 500,
    "path": "/metadata",
    "latency": "167.12µs",
    "error": "no hardware found",
    "time": "2025-04-03T06:26:23Z",
    "caller": "/home/runner/work/hegel/hegel/internal/logger/logger.go:53",
    "message": "all_errors"
}
```
